version: "3.8" 
services: 
  openwebui: 
    container_name: openwebui_host 
    image: ghcr.io/open-webui/open-webui:main 
    environment: 
      GLOBAL_LOG_LEVEL: "debug" 
      ENABLE_RAG_LOCAL_WEB_FETCH: True 
      ENABLE_RAG_WEB_SEARCH: True 
      RAG_EMBEDDING_ENGINE: "ollama" 
      RAG_EMBEDDING_MODEL: "cl-nagoya/ruri-base:latest" 
      RAG_EMBEDDING_BATCH_SIZE: 1 
      RAG_OLLAMA_BASE_URL: "http://host.docker.internal:11434" 
      CHUNK_SIZE: 500 
      CHUNK_OVERLAP: 50 
      RAG_WEB_SEARCH_ENGINE: "searxng" 
      RAG_WEB_SEARCH_RESULT_COUNT: 3 
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10 
      SEARXNG_QUERY_URL: "http://searxng:8080/search?lang=ja&q=<query>" 
    ports: 
      - "3000:8080" 
    volumes: 
      - open-webui:/app/backend/data 
  searxng: 
    container_name: searxng_host 
    image: searxng/searxng:latest 
    ports: 
      - "8080:8080" 
    volumes: 
      - ./searxng:/etc/searxng:rw 
    env_file: 
      - .env 
    restart: unless-stopped 
volumes: 
  open-webui: 